export const housePromptRules = [
  "For a house interpretation, read the house number from deterministicData.unit.id and use this fixed customer meaning:",
  "House 1 — Self and identity: identity, self-presentation, personal style, first impressions and the instinctive approach to life.",
  "House 2 — Money, possessions and values: personal resources, material security, self-worth and what the person considers valuable.",
  "House 3 — Communication and everyday life: communication, learning, siblings, neighbours, short journeys and everyday information exchange.",
  "House 4 — Home, family and roots: home, family, ancestry, private life and emotional foundations.",
  "House 5 — Creativity, pleasure and romance: creativity, play, pleasure, dating, self-expression and children.",
  "House 6 — Work, routines and wellbeing: daily routines, practical work, service, habits, health and maintenance of everyday life.",
  "House 7 — Partnerships and close relationships: committed one-to-one relationships, collaboration, negotiation and qualities met through other people.",
  "House 8 — Intimacy, shared resources and change: intimacy, shared money, trust, vulnerability, inheritance, loss and deep transformation.",
  "House 9 — Beliefs, travel and higher learning: worldview, philosophy, religion, higher education, long-distance travel and broadening experience.",
  "House 10 — Career, reputation and public life: career, vocation, ambition, reputation, responsibility and public contribution.",
  "House 11 — Friendships, community and future goals: friendships, groups, networks, communities, collective causes and long-term hopes.",
  "House 12 — Inner life, retreat and hidden patterns: solitude, retreat, the unconscious, hidden patterns, endings and experiences away from public view.",
  "Use the plain-English life-area name as the title. Never use the zodiac system, the phrase House N, or an internal identifier as the customer-facing title.",
  "Lead the summary with what this means for the person. Do not lead with the cusp sign, ruler, occupants or a generic definition of the house.",
  "Use the supplied cusp sign and ruler as evidence for a personalised interpretation; include occupants and relevant aspects when supplied.",
  "If the house has no occupants, still interpret the cusp sign and ruler. Never treat an empty house as having nothing meaningful to say.",
  "Do not merely list placements. Every technical fact mentioned must immediately support a concrete conclusion about behaviour, needs, choices or recurring patterns.",
  "Across summary and detail, make several direct claims using you or your that remain meaningful even when the astrology labels are removed.",
] as const;
