import type { FieldProfile } from "./field.js";

const romanceFields: Readonly<Record<string, readonly string[]>> = {
  title: [
    "romance",
    "relationship",
    "partnership",
    "love",
    "romance",
    "relación",
    "pareja",
    "amor",
  ],
  summary: [
    "relationship",
    "partnership",
    "bond",
    "love",
    "romance",
    "connection",
    "intimacy",
    "reciprocity",
    "relación",
    "pareja",
    "vínculo",
    "amor",
    "conexión",
    "intimidad",
    "reciprocidad",
  ],
  detail: [
    "relationship",
    "partnership",
    "bond",
    "love",
    "romance",
    "connection",
    "courtship",
    "commitment",
    "attachment",
    "affection",
    "relación",
    "pareja",
    "vínculo",
    "amor",
    "conexión",
    "cortejo",
    "compromiso",
    "apego",
    "afecto",
  ],
  affectionStyle: [
    "affection",
    "warmth",
    "tenderness",
    "touch",
    "care",
    "caring",
    "closeness",
    "devotion",
    "gesture",
    "reassurance",
    "Venus",
    "Moon",
    "afecto",
    "cariño",
    "calidez",
    "ternura",
    "contacto",
    "cuidado",
    "cercanía",
    "devoción",
    "gesto",
    "tranquilidad",
    "Luna",
  ],
  courtshipStyle: [
    "courtship",
    "pursuit",
    "flirting",
    "attraction",
    "initiative",
    "dating",
    "romance",
    "approach",
    "Venus",
    "Mars",
    "cortejo",
    "conquista",
    "coqueteo",
    "atracción",
    "iniciativa",
    "citas",
    "acercamiento",
    "Marte",
  ],
  attachmentNeeds: [
    "attachment",
    "security",
    "reassurance",
    "trust",
    "consistency",
    "closeness",
    "autonomy",
    "space",
    "safety",
    "stability",
    "bond",
    "Moon",
    "Saturn",
    "apego",
    "seguridad",
    "confianza",
    "constancia",
    "cercanía",
    "autonomía",
    "espacio",
    "estabilidad",
    "vínculo",
    "Luna",
    "Saturno",
  ],
  preferredPartnerQualities: [
    "partner",
    "quality",
    "compatibility",
    "trust",
    "communication",
    "stability",
    "affection",
    "independence",
    "pareja",
    "cualidad",
    "compatibilidad",
    "confianza",
    "comunicación",
    "estabilidad",
    "afecto",
    "independencia",
  ],
  relationshipStrengths: [
    "relationship",
    "partnership",
    "bond",
    "support",
    "affection",
    "trust",
    "commitment",
    "relación",
    "pareja",
    "vínculo",
    "apoyo",
    "afecto",
    "confianza",
    "compromiso",
  ],
  relationshipDifficulties: [
    "relationship",
    "partnership",
    "bond",
    "conflict",
    "distance",
    "jealousy",
    "avoidance",
    "pressure",
    "relación",
    "pareja",
    "vínculo",
    "conflicto",
    "distancia",
    "celos",
    "evasión",
    "presión",
  ],
  commitmentPattern: [
    "commitment",
    "loyalty",
    "stability",
    "duration",
    "exclusivity",
    "independence",
    "partnership",
    "compromiso",
    "lealtad",
    "estabilidad",
    "duración",
    "exclusividad",
    "independencia",
    "pareja",
  ],
};

export const fieldProfiles: Readonly<Record<string, FieldProfile>> = {
  sexuality: {
    id: "sexuality",
    lexicon: [
      "Mars",
      "Venus",
      "Pluto",
      "desire",
      "attraction",
      "libido",
      "intimacy",
      "pace",
      "initiation",
      "turn-on",
      "surrender",
      "control",
      "erotic",
      "fifth house",
      "eighth house",
    ],
    minLength: 20,
  },

  career: {
    id: "career",
    lexicon: [
      "vocation",
      "work",
      "authority",
      "ambition",
      "achievement",
      "tenth house",
      "Midheaven",
      "Saturn",
      "Mars",
      "Jupiter",
      "career",
    ],
    minLength: 20,
  },

  romance: {
    id: "romance",
    lexicon: [
      "affection",
      "attachment",
      "courtship",
      "partnership",
      "relationship",
      "bond",
      "love",
      "intimacy",
      "commitment",
      "Venus",
      "Moon",
      "fifth house",
      "seventh house",
      "romance",
      "afecto",
      "apego",
      "cortejo",
      "pareja",
      "relación",
      "vínculo",
      "amor",
      "intimidad",
      "compromiso",
      "Luna",
    ],
    fieldLexicons: romanceFields,
    minLength: 20,
  },

  money: {
    id: "money",
    lexicon: [
      "money",
      "income",
      "earning",
      "spending",
      "security",
      "risk",
      "resources",
      "second house",
      "Saturn",
      "Venus",
    ],
    minLength: 20,
  },
};
